/*
 * generated by tools/export_thai_font.py — do not edit
 *
 * ฟอนต์ไทยที่ประกอบร่างมาแล้วจาก Mac (ADR-0008) firmware แค่วาด codepoint ที่ได้รับ
 * ไม่มีตรรกะภาษาไทยฝั่งนี้แม้บรรทัดเดียว
 */

#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t ct_font_thai_12;
extern const lv_font_t ct_font_thai_14;

#ifdef __cplusplus
}
#endif
