// generated by tools/export_thai.py from tools/thai.toml — do not edit

/// ตารางเลือกร่าง glyph ภาษาไทย — คู่แฝดของ tools/gen/thai_table.py
public enum ThaiTable {
    public enum MarkClass: String {
        case above, tone, below
    }

    public static let blockRanges: [ClosedRange<UInt32>] = [
        0x0E01...0x0E3A,
        0x0E3F...0x0E5B,
    ]

    /// ปฝฟฬ
    public static let tallBases: Set<UInt32> = [0x0E1B, 0x0E1D, 0x0E1F, 0x0E2C]

    /// ญฐ
    public static let descenderBases: Set<UInt32> = [0x0E0D, 0x0E10]

    public static let markClasses: [UInt32: MarkClass] = [
        0x0E31: .above,
        0x0E34: .above,
        0x0E35: .above,
        0x0E36: .above,
        0x0E37: .above,
        0x0E47: .above,
        0x0E4D: .above,
        0x0E4E: .above,
        0x0E48: .tone,
        0x0E49: .tone,
        0x0E4A: .tone,
        0x0E4B: .tone,
        0x0E4C: .tone,
        0x0E38: .below,
        0x0E39: .below,
        0x0E3A: .below,
        0xF700: .above,
        0xF701: .above,
        0xF702: .above,
        0xF703: .above,
        0xF704: .above,
        0xF705: .above,
        0xF706: .above,
        0xF707: .above,
        0xF708: .tone,
        0xF709: .tone,
        0xF70A: .tone,
        0xF70B: .tone,
        0xF70C: .tone,
        0xF70D: .tone,
        0xF70E: .tone,
        0xF70F: .tone,
        0xF710: .tone,
        0xF711: .tone,
        0xF712: .tone,
        0xF713: .tone,
        0xF714: .tone,
        0xF715: .tone,
        0xF716: .tone,
        0xF717: .below,
        0xF718: .below,
        0xF719: .below,
    ]

    /// ร่างที่เลือกแล้ว -> ร่างปกติ ทำให้การประกอบร่างซ้ำได้ผลเดิม
    public static let canonical: [UInt32: UInt32] = [
        0xF700: 0x0E31,
        0xF701: 0x0E34,
        0xF702: 0x0E35,
        0xF703: 0x0E36,
        0xF704: 0x0E37,
        0xF705: 0x0E47,
        0xF706: 0x0E4D,
        0xF707: 0x0E4E,
        0xF708: 0x0E48,
        0xF709: 0x0E49,
        0xF70A: 0x0E4A,
        0xF70B: 0x0E4B,
        0xF70C: 0x0E4C,
        0xF70D: 0x0E48,
        0xF70E: 0x0E49,
        0xF70F: 0x0E4A,
        0xF710: 0x0E4B,
        0xF711: 0x0E4C,
        0xF712: 0x0E48,
        0xF713: 0x0E49,
        0xF714: 0x0E4A,
        0xF715: 0x0E4B,
        0xF716: 0x0E4C,
        0xF717: 0x0E38,
        0xF718: 0x0E39,
        0xF719: 0x0E3A,
    ]

    public static let variants: [String: [UInt32: UInt32]] = [
        "above_tall": [
            0x0E31: 0xF700,
            0x0E34: 0xF701,
            0x0E35: 0xF702,
            0x0E36: 0xF703,
            0x0E37: 0xF704,
            0x0E47: 0xF705,
            0x0E4D: 0xF706,
            0x0E4E: 0xF707,
        ],
        "tone_tall": [
            0x0E48: 0xF708,
            0x0E49: 0xF709,
            0x0E4A: 0xF70A,
            0x0E4B: 0xF70B,
            0x0E4C: 0xF70C,
        ],
        "tone_high": [
            0x0E48: 0xF70D,
            0x0E49: 0xF70E,
            0x0E4A: 0xF70F,
            0x0E4B: 0xF710,
            0x0E4C: 0xF711,
        ],
        "tone_tall_high": [
            0x0E48: 0xF712,
            0x0E49: 0xF713,
            0x0E4A: 0xF714,
            0x0E4B: 0xF715,
            0x0E4C: 0xF716,
        ],
        "below_descender": [
            0x0E38: 0xF717,
            0x0E39: 0xF718,
            0x0E3A: 0xF719,
        ],
    ]
}
