#!/usr/bin/env python3
"""thai.toml -> ตารางเลือกร่าง glyph ทั้งฝั่ง Swift และฝั่ง Python

เหตุผลเดียวกับ export_layout.py: อัลกอริทึมเดินคลัสเตอร์ถูกพอร์ตสองฝั่ง
(daemon เป็น Swift, preview.py เป็น Python) ถ้าตารางไม่ได้มาจากไฟล์เดียวกัน
ทั้งสองฝั่งจะดริฟต์ออกจากกันเงียบๆ แล้ว preview จะเลิกเป็นหลักฐาน

    python3 tools/export_thai.py

**ห้ามแก้ไฟล์ที่ generate ออกมา** — แก้ thai.toml แล้วรันใหม่
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
REPO_DIR = TOOLS_DIR.parent
THAI_TOML = TOOLS_DIR / "thai.toml"

PY_OUT = TOOLS_DIR / "gen" / "thai_table.py"
SWIFT_OUT = REPO_DIR / "host" / "Sources" / "TamaCore" / "ThaiTable.swift"

BANNER = "generated by tools/export_thai.py from tools/thai.toml — do not edit"


def load() -> dict:
    with THAI_TOML.open("rb") as fh:
        return tomllib.load(fh)


def assign_pua(raw: dict) -> dict[str, dict[int, int]]:
    """ร่างที่ไม่ใช่ร่างปกติ -> codepoint ใน PUA

    ลำดับการแจกต้องขึ้นกับลำดับใน thai.toml เท่านั้น ไม่ใช่ลำดับของ dict ที่บังเอิญได้มา
    ไม่งั้นการเพิ่มร่างใหม่จะขยับ codepoint ของร่างเดิมทั้งชุด แล้วฟอนต์ที่แฟลชไว้แล้ว
    กับ daemon ที่เพิ่งคอมไพล์จะพูดคนละภาษา
    """
    next_cp = raw["font"]["pua_start"]
    out: dict[str, dict[int, int]] = {}
    for v in raw["variant"]:
        chars = raw["mark"][v["class"]]
        table: dict[int, int] = {}
        for ch in chars:
            table[ord(ch)] = next_cp
            next_cp += 1
        out[v["name"]] = table
    return out


def _mark_classes(raw: dict, pua: dict[str, dict[int, int]]) -> dict[int, str]:
    """อักขระที่กว้างศูนย์ทั้งหมด — ทั้งร่างปกติและร่างที่เลือกแล้ว

    ร่างใน PUA ต้องอยู่ในตารางนี้ด้วย ไม่งั้นการนับความกว้างของข้อความที่ประกอบร่าง
    ไปแล้วจะนับวรรณยุกต์เป็นหนึ่งช่อง แล้วข้อความไทยจะถูกตัดสั้นเกินจริงอีกทาง
    """
    out: dict[int, str] = {}
    klass_of: dict[str, str] = {v["name"]: v["class"] for v in raw["variant"]}
    for klass in ("above", "tone", "below"):
        for ch in raw["mark"][klass]:
            out[ord(ch)] = klass
    for name, table in pua.items():
        for cp in table.values():
            out[cp] = klass_of[name]
    return out


def _canonical(pua: dict[str, dict[int, int]]) -> dict[int, int]:
    return {cp: src for table in pua.values() for src, cp in table.items()}


def _py(raw: dict, pua: dict[str, dict[int, int]]) -> str:
    lines = [
        f'"""{BANNER}"""',
        "",
        "from __future__ import annotations",
        "",
        "BLOCK_RANGES = [",
    ]
    for lo, hi in raw["block"]["ranges"]:
        lines.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
    lines.append("]")
    lines.append("")
    for key, name in (("tall", "TALL_BASES"), ("descender", "DESCENDER_BASES")):
        items = ", ".join(f"0x{ord(c):04X}" for c in raw["base"][key])
        lines.append(f"{name} = {{{items}}}  # {''.join(raw['base'][key])}")
    lines.append("")
    lines.append("MARK_CLASSES = {")
    for cp, klass in _mark_classes(raw, pua).items():
        lines.append(f'    0x{cp:04X}: "{klass}",')
    lines.append("}")
    lines.append("")
    lines.append("# ร่างที่เลือกแล้ว -> ร่างปกติ ทำให้การประกอบร่างซ้ำได้ผลเดิม")
    lines.append("CANONICAL = {")
    for cp, src in _canonical(pua).items():
        lines.append(f"    0x{cp:04X}: 0x{src:04X},")
    lines.append("}")
    lines.append("")
    lines.append("VARIANTS = {")
    for name, table in pua.items():
        lines.append(f'    "{name}": {{')
        for src, cp in table.items():
            lines.append(f"        0x{src:04X}: 0x{cp:04X},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _swift(raw: dict, pua: dict[str, dict[int, int]]) -> str:
    lines = [
        f"// {BANNER}",
        "",
        "/// ตารางเลือกร่าง glyph ภาษาไทย — คู่แฝดของ tools/gen/thai_table.py",
        "public enum ThaiTable {",
        "    public enum MarkClass: String {",
        "        case above, tone, below",
        "    }",
        "",
        "    public static let blockRanges: [ClosedRange<UInt32>] = [",
    ]
    for lo, hi in raw["block"]["ranges"]:
        lines.append(f"        0x{lo:04X}...0x{hi:04X},")
    lines.append("    ]")
    lines.append("")
    for key, name in (("tall", "tallBases"), ("descender", "descenderBases")):
        items = ", ".join(f"0x{ord(c):04X}" for c in raw["base"][key])
        lines.append(f"    /// {''.join(raw['base'][key])}")
        lines.append(f"    public static let {name}: Set<UInt32> = [{items}]")
        lines.append("")
    lines.append("    public static let markClasses: [UInt32: MarkClass] = [")
    for cp, klass in _mark_classes(raw, pua).items():
        lines.append(f"        0x{cp:04X}: .{klass},")
    lines.append("    ]")
    lines.append("")
    lines.append("    /// ร่างที่เลือกแล้ว -> ร่างปกติ ทำให้การประกอบร่างซ้ำได้ผลเดิม")
    lines.append("    public static let canonical: [UInt32: UInt32] = [")
    for cp, src in _canonical(pua).items():
        lines.append(f"        0x{cp:04X}: 0x{src:04X},")
    lines.append("    ]")
    lines.append("")
    lines.append("    public static let variants: [String: [UInt32: UInt32]] = [")
    for name, table in pua.items():
        lines.append(f'        "{name}": [')
        for src, cp in table.items():
            lines.append(f"            0x{src:04X}: 0x{cp:04X},")
        lines.append("        ],")
    lines.append("    ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    raw = load()
    pua = assign_pua(raw)
    PY_OUT.write_text(_py(raw, pua), encoding="utf-8")
    SWIFT_OUT.write_text(_swift(raw, pua), encoding="utf-8")
    total = sum(len(t) for t in pua.values())
    print(f"{PY_OUT.relative_to(REPO_DIR)}  <- {total} variant glyphs")
    print(f"{SWIFT_OUT.relative_to(REPO_DIR)}  <- {total} variant glyphs")


if __name__ == "__main__":
    sys.exit(main())
